name: toolshare_portal
description: A tool sharing portal that allows peers to earn extra income via renting tools


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.1.1
  flutter_speed_dial: ^6.2.0 
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  google_fonts: ^3.0.1
  http: ^0.13.5
  image_cropper: ^3.0.1
  image_picker: ^0.8.6
  file_picker: ^5.2.11
  open_file: ^3.3.1
  google_nav_bar: ^5.0.6
  intl: ^0.18.0
  ndialog: ^4.2.2
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1 
  url_launcher: ^6.1.11
  google_maps_flutter: ^2.2.6
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/

  uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
